TaskTracker/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.template.context_processors import static
from django.urls import path, include
from django.views.generic import RedirectView

from TaskTracker.views import page_not_found, redirect_login, redirect_home
from users.views import logout_user

urlpatterns = [
    path('', redirect_home, name='index'),
    path('login', redirect_login, name='login'),
    path('logout', logout_user, name='logout'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'))),
    path('projects/', include(('tasks.urls', 'tasks'))),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("img/icons8-task-100.png")), name="favicon")
]

handler404 = page_not_found

tasks/urls.py
from django.urls import path

from tasks import views

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('add_project', views.AddProjectView.as_view(), name='add_project'),
    path('<int:pk>/update', views.UpdateProjectView.as_view(), name='update_project'),
    path('<int:pk>/add_task', views.AddTaskView.as_view(), name='add_task'),
    path('<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('update_status/<int:task_id>', views.update_status, name='update_status'),
    path('tasks/delete/<int:task_id>', views.delete_task, name='delete_task'),
    path('tasks/update/<int:pk>', views.UpdateTaskView.as_view(), name='update_task'),
    path('<int:project_id>/statistics', views.project_statistics, name='project_statistics'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    TEAMLEAD = 'teamlead'
    DIRECTOR = 'director'
    DEVELOPER = 'developer'

    ROLE_CHOICES = [
        (TEAMLEAD, 'Team Lead'),
        (DIRECTOR, 'Director'),
        (DEVELOPER, 'Developer'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=DEVELOPER)

    def __str__(self):
        return self.username

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">

    <link rel="icon" type="image/png" href="{% url 'favicon' %} ">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body class="mx-3 ">

<header class="row align-items-center">
    <div class="col-md-4">
        {% if user.is_authenticated %}
            <div class="row">
                <a href="{% url 'users:logout' %}" class="col-2 btn btn-outline-danger">Выйти</a>
                <a href="{% url 'users:user_page' username=user.username %}" class="col-8 link-opacity-50-hover link fs-3">{{ user.username }}</a>
            </div>

        {% else %}
            <a href="{% url 'users:login' %}" class="btn btn-outline-primary">Войти</a>
        {% endif %}
    </div>
    <div class="col-md-4 text-center">
        <h1>{{ title }}</h1>
    </div>
    <nav class="col-md-4 text-end">
        <a href="{% url 'users:user_list' %}" class="btn btn-outline-primary">Разработчики</a>
        <a href="{% url 'tasks:project_list' %}" class="btn btn-outline-primary">Проекты</a>
    
        {% if request.user.is_authenticated and request.user.role != 'director' %}
            <a href="{% url 'users:user_page' username=user.username %}" class="btn btn-outline-primary">Ваши задачи</a>
        {% endif %}
    </nav>
    <hr class="col-md-12">
</header>


<main class="mx-4 me-3">
    {% block content %}

    {% endblock %}
</main>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>
</html>