TaskTracker/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.template.context_processors import static
from django.urls import path, include
from django.views.generic import RedirectView

from TaskTracker.views import page_not_found, redirect_login, redirect_home
from users.views import logout_user

urlpatterns = [
    path('', redirect_home, name='index'),
    path('login', redirect_login, name='login'),
    path('logout', logout_user, name='logout'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'))),
    path('projects/', include(('tasks.urls', 'tasks'))),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("img/icons8-task-100.png")), name="favicon")
]

handler404 = page_not_found

tasks/urls.py
from django.urls import path

from tasks import views

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('add_project', views.AddProjectView.as_view(), name='add_project'),
    path('<int:pk>/update', views.UpdateProjectView.as_view(), name='update_project'),
    path('<int:pk>/add_task', views.AddTaskView.as_view(), name='add_task'),
    path('<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('update_status/<int:task_id>', views.update_status, name='update_status'),
    path('tasks/delete/<int:task_id>', views.delete_task, name='delete_task'),
    path('tasks/update/<int:pk>', views.UpdateTaskView.as_view(), name='update_task'),
    path('<int:project_id>/statistics', views.project_statistics, name='project_statistics'),
]

users/urls.py
from django.urls import path

import users.views as views

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout', views.logout_user, name='logout'),
    path('', views.UserList.as_view(), name='user_list'),
    path('<str:username>', views.UserPage.as_view(), name='user_page'),
]

tasks/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField()

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE)

    STATUS_CHOICES = [
        ('todo', 'To Do'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='todo')

    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='medium')

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    TEAMLEAD = 'teamlead'
    DIRECTOR = 'director'
    DEVELOPER = 'developer'

    ROLE_CHOICES = [
        (TEAMLEAD, 'Team Lead'),
        (DIRECTOR, 'Director'),
        (DEVELOPER, 'Developer'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=DEVELOPER)

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
import django.forms

from users.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    role = forms.ChoiceField(choices=User.ROLE_CHOICES)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'role']

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView

from users.forms import LoginUserForm
from users.models import User


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('index'))


class UserList(ListView):
    model = User
    template_name = 'users/list.html'
    context_object_name = 'users'
    extra_context = {'title': 'Список пользователей'}


class UserPage(DetailView):
    model = User
    template_name = 'users/user_page.html'
    context_object_name = 'user_p'

    def get_object(self, queryset=None):
        username = self.kwargs['username']
        # Получаем объект пользователя по его имени пользователя (username)
        return get_object_or_404(User, username=username, is_superuser=False)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs['username']
        context['title'] = f'Профиль {username}'
        return context

templates/users/list.html
{% extends 'base.html' %}
{% load tags %}
{% block content %}
    <div class="container">
        <ul class="list-group">
            {% for user in object_list|sort_by:"role" %}
                {% if not user.is_superuser %}
                    <li class="list-group-item d-flex justify-content-between align-items-center fs-2">
                        <a href="{% url 'users:user_page' username=user.username %}">{{ user.username }}</a>
                        <span class="badge bg-primary rounded-pill">{{ user.get_role_display }}</span>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <form method="post" class="login-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>
  </div>
{% endblock %}

templates/users/user_page.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1 class="fs-1">{{ user_p.username }}</h1>
        <div class="row">
            <div class="col-md-6 fs-5">
                <p><strong>Email:</strong> {{ user_p.email }}</p>
                <p><strong>First Name:</strong> {{ user_p.first_name }}</p>
                <p><strong>Last Name:</strong> {{ user_p.last_name }}</p>
                <p><strong>Role:</strong> {{ user_p.get_role_display }}</p>
            </div>
        </div>

        <hr>

        {% if user_p.role == 'teamlead' %}
            <div class="row mt-4">
                <div class="col-md-12">
                    <h2>Проекты</h2>

                    {% include 'elems/tasks/project_list.html' with projects=user_p.project_set.all %}

                </div>
            </div>
        {% elif user_p.role == 'developer' %}
            <div class="row mt-4">
                <div class="col-md-12">
                    <h2>Задачи</h2>

                    {% include 'elems/tasks/task_list.html' with tasks=user_p.task_set.all %}

                </div>
            </div>
        {% endif %}

    <hr>
    </div>
{% endblock %}